### ISSUE TITLE
Randomly generates different code

### ISSUE THREAD

**Issue by dholm** [glycerine/greenpack#8] opened 2018-04-16 14:44 UTC
When calling `greenpack` multiple times with the same input it will randomly generate different output.  To reproduce, use `greenpack-bug.go` from [this gist](https://gist.github.com/dholm/66d5c60014cfc43d527bfc5904648733) and then call the following command repeatedly:

```
greenpack -io=false -marshal=true -omit-clue -file greenpack-bug.go; \
  mv greenpack-bug_gen.go greenpack-bug_gen.go.1; \
  greenpack -io=false -marshal=true -omit-clue -file greenpack-bug.go; \
  diff -aur greenpack-bug_gen.go.1 greenpack-bug_gen.go
```

It generates a difference about once in every three calls when I try it.  I have also attached a diff in the gist.

I think it's being caused by Go's [random map iteration order](https://nathanleclaire.com/blog/2014/04/27/a-surprising-feature-of-golang-that-colored-me-impressed/) because if I sort the keys in `propInline` (`parse/inline.go`) and then use the sorted keys in the iteration of `f.Identities` the generated file is identical every time.  However, I do not know if this is the correct solution as I'm not familiar enough with the `greenpack` implementation.

**Comment by glycerine** [comment] 2018-04-16 16:15
Thanks for writing in David.

The deterministic ordering depends on using zid struct tags. You have commented out your struct tags, therefore they are not being applied.

not this:
~~~
type Struct1 struct {
	I I64  // `zid:"0"`
	S Str1 // `zid:"1"`
}
~~~
but instead do:
~~~
type Struct1 struct {
	I I64  `zid:"0"`
	S Str1 `zid:"1"`
}
~~~

**Comment by dholm** [comment] 2018-04-17 07:31
That was embarrassingly simple.  Since there was such a large difference in the generated code I was looking for a complicated solution.  Thanks for helping me resolve it so quickly!

**Comment by dholm** [comment] 2018-04-17 08:05
I'm still having issues after uncommenting the zids actually.  `greenpack` will still generate different output about once every three runs.  I have created a new [gist](https://gist.github.com/dholm/a1b8821e1c1b4dfc1caaf67aa4c2c43a) with an updated file for reproducing the problem.  It only happens if I have a `struct` embedded in another `struct`.

Am I still using `greenpack` incorrectly or is this an actual issue?

**Comment by glycerine** [comment] 2018-04-17 13:00
Bizarre indeed. Sorry for closing this too soon. Looking into it now. That inlining is involved is very a good clue, since that decision is made at runtime based on the complexity and content of the input.

**Comment by glycerine** [comment] 2018-04-17 13:05
I can reproduce. Almost certainly its the inlining, even the printed output of `go generate` refects this. Compare one run
~~~
======== Greenpack Code Generator  =======
>>> Input: "hmm.go"
hmm.go: Struct1: inlining I1
hmm.go: Struct1: inlining Str
>>> Wrote and formatted "hmm_gen_test.go"
>>> Wrote and formatted "hmm_gen.go"
~~~
versus another run where Struct1 got inlined
~~~
======== Greenpack Code Generator  =======
>>> Input: "hmm.go"
hmm.go: Struct2: inlining Struct1
hmm.go: Struct2: inlining I1
hmm.go: Struct2: inlining Str
hmm.go: Struct1: inlining I1
hmm.go: Struct1: inlining Str
>>> Wrote and formatted "hmm_gen_test.go"
>>> Wrote and formatted "hmm_gen.go"
~~~

**Comment by glycerine** [comment] 2018-04-17 13:17
It appears to have to do with the order in which structs themselves are processed, since if Struct1 is treated first and inlined, then its complexity goes over threshold. Whereas if Struct2 is treated first, Struct1 is simpler at that point (without having had inlining applied), and Struct1 is inlined into struct2.

~~~
jaten@Jasons-MacBook-Pro ~/hmm $ go generate hmm.go
======== Greenpack Code Generator  =======
>>> Input: "hmm.go"
hmm.go: Struct1: inlining I1, complexity was 2 < 5
hmm.go: Struct1: inlining Str, complexity was 2 < 5
hmm.go: Struct2: NOT inlining Struct1, complexity was 5 >= 5
>>> Wrote and formatted "hmm_gen_test.go"
>>> Wrote and formatted "hmm_gen.go"
jaten@Jasons-MacBook-Pro ~/hmm $ go generate hmm.go
======== Greenpack Code Generator  =======
>>> Input: "hmm.go"
hmm.go: Struct2: inlining Struct1, complexity was 3 < 5
hmm.go: Struct2: inlining I1, complexity was 2 < 5
hmm.go: Struct2: inlining Str, complexity was 2 < 5
hmm.go: Struct1: inlining I1, complexity was 2 < 5
hmm.go: Struct1: inlining Str, complexity was 2 < 5
>>> Wrote and formatted "hmm_gen_test.go"
>>> Wrote and formatted "hmm_gen.go"
jaten@Jasons-MacBook-Pro ~/hmm $  
~~~

**Comment by glycerine** [comment] 2018-04-17 14:02
@dholm Give the latest a try. Should be fixed.

**Closed as completed** 2018-04-17 14:02 UTC

**Comment by dholm** [comment] 2018-04-17 14:17
@glycerine That seems to have done the trick.  Thanks for fixing it so fast!
