### ISSUE TITLE
msgp: type "map[string][]float64" not supported

### ISSUE THREAD

**Issue by chrislusf** [glycerine/greenpack#1] opened 2017-09-03 15:36 UTC
How to support this more nested structure?

This is related to https://github.com/chrislusf/gleam/issues/61

**Comment by glycerine** [comment] 2017-09-03 15:39
Seems to work for me. Can you post a reproduction of the error?

This code passes `go generate` followed by `go test` just fine.
~~~
package main

import (
    "fmt"
)

//go:generate greenpack                                                                                          

type King struct {
    M map[string][]float64
}

var p = fmt.Printf

func main() {
    p("a = %#v\n", King{})
}
~~~

**Comment by glycerine** [comment] 2017-09-03 15:48
Given the error message on https://github.com/chrislusf/gleam/issues/61, I suspect you are writing to an interface where write to a concrete type would succeed.

**Comment by chrislusf** [comment] 2017-09-03 16:02
I am using row.MarshalMsg(nil), where the function is generated via "go generate"

https://github.com/chrislusf/gleam/blob/master/util/row.go#L4

**Comment by glycerine** [comment] 2017-09-03 16:05
ah, slices of interface{}. hmm...

**Comment by chrislusf** [comment] 2017-09-03 16:06
I can reproduce it in my own package.

    package util

    import (
        "testing"
    )

    func TestMap(t *testing.T) {
        m := make(map[string][]float64)
        m["def"] = []float64{1.2, 3.4}

        row := Row{}
        row.K = []interface{}{"abc"}
        row.V = []interface{}{m}
        encoded, err := encodeRow(row)
        t.Logf("encoded row: %x", encoded)
        if err != nil {
            t.Fatal(err)
        }
    }

    /* this function in my own pacakge is referenced.

    func encodeRow(row Row) ([]byte, error) {
        return row.MarshalMsg(nil)
    }

    */

**Comment by glycerine** [comment] 2017-09-03 16:07
looking...

**Comment by glycerine** [comment] 2017-09-03 16:37
so at present, unless you wrap the map in a named struct that we generate code for, only two kinds of map values are supported, string and interface{}.  Fortunately interface{} is pretty universal.

if you change this line
~~~
m := make(map[string][]float64)
~~~
to this:
~~~
m := make(map[string]interface{})
~~~
then it will all work.

**Comment by glycerine** [comment] 2017-09-03 16:40
Let me know if one of those two solutions works for you.

i.e. Either interpose a named struct, or change to map[string]interface{}.

**Comment by chrislusf** [comment] 2017-09-03 16:49
Understood. "map[string]interface{}" could be a workaround for the user. 

But ideally, the map values should not be so generic, loosing the strong typing.

**Comment by glycerine** [comment] 2017-09-03 17:10
I just pushed an attempt at a remedy in 

1fb9b33adff0c44fa7013f92827146ffe03509c2

please pull the latest and try it. It passes on the test case we've been discussing, but there may still be hidden corners.

**Comment by glycerine** [comment] 2017-09-03 17:19
Since the latest release supports this case now, I'm going to close this ticket. But I'm still very interested in knowing if you find any residual issue. Please feel free to comment here and I will re-open if its not solved.

**Closed as completed by glycerine** 2017-09-03 17:19 UTC
